-- 99: client voice notes 03-Oct-2026 — yarn / fabric process and knitting job-work bills work like the purchase bill:
--   gate entry, party bill date, due date, GST nature (CGST+SGST / IGST), freight, other charges (±, label), TDS, TCS,
--   round off, and a match status (GRN / rate vs quotation / gate). Bills saved before stay calc_version 1.
-- Re-runnable.

SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='party_bill_date');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN party_bill_date DATE NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='due_date');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN due_date DATE NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='gate_inward_id');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN gate_inward_id BIGINT UNSIGNED NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='gst_type');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN gst_type VARCHAR(20) NOT NULL DEFAULT ''INTRA_STATE''', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='debit_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN debit_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='taxable_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN taxable_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='cgst_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN cgst_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='sgst_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN sgst_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='igst_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN igst_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='freight_charges');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN freight_charges DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='other_charges_sign');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN other_charges_sign TINYINT NOT NULL DEFAULT 1', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='other_charges_label');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN other_charges_label VARCHAR(80) NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='tds_section');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN tds_section VARCHAR(20) NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='tds_pct');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN tds_pct DECIMAL(6,3) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='tds_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN tds_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='tcs_section');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN tcs_section VARCHAR(20) NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='tcs_pct');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN tcs_pct DECIMAL(6,3) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='tcs_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN tcs_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='round_off');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN round_off DECIMAL(10,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='match_status');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN match_status VARCHAR(20) NULL COMMENT ''FULLY_MATCHED / PARTIAL / DISCREPANCY''', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_fabric_process_bill' AND COLUMN_NAME='calc_version');
SET @s = IF(@x=0, 'ALTER TABLE trx_fabric_process_bill ADD COLUMN calc_version TINYINT NOT NULL DEFAULT 1 COMMENT ''1 = other charges taxed (old), 2 = invoice summary (other charges after GST)''', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
UPDATE trx_fabric_process_bill SET taxable_amount = net_amount - gst_amount WHERE calc_version = 1 AND taxable_amount = 0 AND net_amount <> 0;
UPDATE trx_fabric_process_bill SET cgst_amount = ROUND(gst_amount / 2, 2), sgst_amount = gst_amount - ROUND(gst_amount / 2, 2) WHERE calc_version = 1 AND cgst_amount = 0 AND igst_amount = 0 AND gst_amount <> 0;

SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='party_bill_date');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN party_bill_date DATE NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='due_date');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN due_date DATE NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='gate_inward_id');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN gate_inward_id BIGINT UNSIGNED NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='gst_type');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN gst_type VARCHAR(20) NOT NULL DEFAULT ''INTRA_STATE''', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='debit_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN debit_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='taxable_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN taxable_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='cgst_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN cgst_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='sgst_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN sgst_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='igst_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN igst_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='freight_charges');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN freight_charges DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='other_charges_sign');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN other_charges_sign TINYINT NOT NULL DEFAULT 1', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='other_charges_label');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN other_charges_label VARCHAR(80) NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='tds_section');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN tds_section VARCHAR(20) NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='tds_pct');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN tds_pct DECIMAL(6,3) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='tds_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN tds_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='tcs_section');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN tcs_section VARCHAR(20) NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='tcs_pct');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN tcs_pct DECIMAL(6,3) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='tcs_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN tcs_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='round_off');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN round_off DECIMAL(10,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='match_status');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN match_status VARCHAR(20) NULL COMMENT ''FULLY_MATCHED / PARTIAL / DISCREPANCY''', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_yarn_process_bill' AND COLUMN_NAME='calc_version');
SET @s = IF(@x=0, 'ALTER TABLE trx_yarn_process_bill ADD COLUMN calc_version TINYINT NOT NULL DEFAULT 1 COMMENT ''1 = other charges taxed (old), 2 = invoice summary (other charges after GST)''', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
UPDATE trx_yarn_process_bill SET taxable_amount = net_amount - gst_amount WHERE calc_version = 1 AND taxable_amount = 0 AND net_amount <> 0;
UPDATE trx_yarn_process_bill SET cgst_amount = ROUND(gst_amount / 2, 2), sgst_amount = gst_amount - ROUND(gst_amount / 2, 2) WHERE calc_version = 1 AND cgst_amount = 0 AND igst_amount = 0 AND gst_amount <> 0;

SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='party_bill_date');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN party_bill_date DATE NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='due_date');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN due_date DATE NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='gate_inward_id');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN gate_inward_id BIGINT UNSIGNED NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='gst_type');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN gst_type VARCHAR(20) NOT NULL DEFAULT ''INTRA_STATE''', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='debit_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN debit_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='taxable_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN taxable_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='cgst_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN cgst_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='sgst_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN sgst_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='igst_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN igst_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='freight_charges');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN freight_charges DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='other_charges_sign');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN other_charges_sign TINYINT NOT NULL DEFAULT 1', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='other_charges_label');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN other_charges_label VARCHAR(80) NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='tds_section');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN tds_section VARCHAR(20) NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='tds_pct');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN tds_pct DECIMAL(6,3) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='tds_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN tds_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='tcs_section');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN tcs_section VARCHAR(20) NULL', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='tcs_pct');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN tcs_pct DECIMAL(6,3) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='tcs_amount');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN tcs_amount DECIMAL(18,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='round_off');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN round_off DECIMAL(10,2) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='match_status');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN match_status VARCHAR(20) NULL COMMENT ''FULLY_MATCHED / PARTIAL / DISCREPANCY''', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @x = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trx_knitting_bill' AND COLUMN_NAME='calc_version');
SET @s = IF(@x=0, 'ALTER TABLE trx_knitting_bill ADD COLUMN calc_version TINYINT NOT NULL DEFAULT 1 COMMENT ''1 = other charges taxed (old), 2 = invoice summary (other charges after GST)''', 'SELECT 1');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
UPDATE trx_knitting_bill SET taxable_amount = net_amount - gst_amount WHERE calc_version = 1 AND taxable_amount = 0 AND net_amount <> 0;
UPDATE trx_knitting_bill SET cgst_amount = ROUND(gst_amount / 2, 2), sgst_amount = gst_amount - ROUND(gst_amount / 2, 2) WHERE calc_version = 1 AND cgst_amount = 0 AND igst_amount = 0 AND gst_amount <> 0;

